### ISSUE TITLE
红米 android 4.4 crash

### ISSUE THREAD

**Issue by switch-st** [switch-iot/n2n_vLTS#1]
配置MTU小于1300时，点击开始运行后crash
### crash message 1
`HM NOTE 1 LTE`
java.lang.RuntimeException: Unable to start service wang.switchy.an2n.service.N2NService@423f7ff8 with Intent { cmp=wang.switchy.an2n/.service.N2NService (has extras) }: **java.lang.IllegalStateException: command '87 interface fwmark rule add tun0' failed with '400 87 Failed to add fwmark rule (Success)'**
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2721)
	at android.app.ActivityThread.access$2100(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: command '87 interface fwmark rule add tun0' failed with '400 87 Failed to add fwmark rule (Success)'
	at android.os.Parcel.readException(Parcel.java:1497)
	at android.os.Parcel.readException(Parcel.java:1443)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1639)
	at android.net.VpnService$Builder.establish(VpnService.java:472)
	at wang.switchy.an2n.service.N2NService.onStartCommand(N2NService.java:79)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
	... 10 more
java.lang.IllegalStateException: command '87 interface fwmark rule add tun0' failed with '400 87 Failed to add fwmark rule (Success)'
	at android.os.Parcel.readException(Parcel.java:1497)
	at android.os.Parcel.readException(Parcel.java:1443)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1639)
	at android.net.VpnService$Builder.establish(VpnService.java:472)
	at wang.switchy.an2n.service.N2NService.onStartCommand(N2NService.java:79)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
	at android.app.ActivityThread.access$2100(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

### crash message 2
`HM NOTE 1 LTE`
java.lang.RuntimeException: Unable to start service wang.switchy.an2n.service.N2NService@423c50f0 with Intent { cmp=wang.switchy.an2n/.service.N2NService (has extras) }: **java.lang.IllegalStateException: command '2309 interface fwmark rule add tun0' failed with '400 2309 Failed to add fwmark rule (File exists)'**
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2721)
	at android.app.ActivityThread.access$2100(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: command '2309 interface fwmark rule add tun0' failed with '400 2309 Failed to add fwmark rule (File exists)'
	at android.os.Parcel.readException(Parcel.java:1497)
	at android.os.Parcel.readException(Parcel.java:1443)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1639)
	at android.net.VpnService$Builder.establish(VpnService.java:472)
	at wang.switchy.an2n.service.N2NService.onStartCommand(N2NService.java:79)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
	... 10 more
java.lang.IllegalStateException: command '2309 interface fwmark rule add tun0' failed with '400 2309 Failed to add fwmark rule (File exists)'
	at android.os.Parcel.readException(Parcel.java:1497)
	at android.os.Parcel.readException(Parcel.java:1443)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1639)
	at android.net.VpnService$Builder.establish(VpnService.java:472)
	at wang.switchy.an2n.service.N2NService.onStartCommand(N2NService.java:79)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
	at android.app.ActivityThread.access$2100(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by switch-st** [comment]
内核问题，系统启动VPN时，设置iptables出错
在builder中，调用establish时加上try ... catch，根据异常的不同，提示用户系统错误或配置异常
