### ISSUE TITLE
"Unfortunately, Hin2n has stopped" while trying to launch the app on an android 5.1 device.

### ISSUE THREAD

**Issue by Abdalnablse10** [switch-iot/n2n_vLTS#71]
First I tried the provided apk file provided in the releases page which sadly didn't work.
So I tried to build it from source on android studio but sadly same thing but it gave me this error log:

12/19 04:27:29: Launching 'app' on samsung SM-T280.
Install successfully finished in 1 m 11 s 112 ms.
$ adb shell am start -n "wang.switchy.hin2n/wang.switchy.hin2n.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 8092 on device 'samsung-sm_t280-52007f6cc0548500'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/Zygote: MountEmulatedStorage()
E/Zygote: v2
I/SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-T280_5.1.1_0072
E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
I/art: Late-enabling -Xcheck:jni
I/libpersona: KNOX_SDCARD checking this for 10129
I/libpersona: KNOX_SDCARD not a persona
W/linker: libslog.so: unused DT entry: type 0x6ffffef5 arg 0x578
W/linker: libslog.so: unused DT entry: type 0x6ffffffe arg 0x6ec
W/linker: libslog.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libuip.so: unused DT entry: type 0x6ffffef5 arg 0x7dc
W/linker: libuip.so: unused DT entry: type 0x6ffffffe arg 0xb30
W/linker: libuip.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libn2n_v2s.so: unused DT entry: type 0x6ffffef5 arg 0x1e2c
W/linker: libn2n_v2s.so: unused DT entry: type 0x6ffffffe arg 0x2bc0
W/linker: libn2n_v2s.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libn2n_v1.so: unused DT entry: type 0x6ffffef5 arg 0x13d0
W/linker: libn2n_v1.so: unused DT entry: type 0x6ffffffe arg 0x1c74
W/linker: libn2n_v1.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libedge_v2s.so: unused DT entry: type 0x6ffffef5 arg 0x11c8
W/linker: libedge_v2s.so: unused DT entry: type 0x6ffffffe arg 0x1778
W/linker: libedge_v2s.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libedge_v2.so: unused DT entry: type 0x6ffffef5 arg 0x2188
W/linker: libedge_v2.so: unused DT entry: type 0x6ffffffe arg 0x3118
W/linker: libedge_v2.so: unused DT entry: type 0x6fffffff arg 0x3
E/art: dlopen("/data/app/wang.switchy.hin2n-1/lib/arm/libedge_v2.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "EVP_CIPHER_CTX_reset" referenced by "libedge_v2.so"...
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: wang.switchy.hin2n, PID: 8092
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "EVP_CIPHER_CTX_reset" referenced by "libedge_v2.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at wang.switchy.hin2n.Hin2nApplication.<clinit>(Hin2nApplication.java:43)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1690)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1018)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1003)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:651)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6007)
        at android.app.ActivityThread.access$1700(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6939)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
I/Process: Sending signal. PID: 8092 SIG: 9

I used windows 11 btw "linux partition had a lack of storage"
"I didn't use the "code text format" because it mixed everything together in preview making it harder to read"

**Comment by lucktu** [comment]
Android 5.1 is too old. get a newer system.
